# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Alan Tai <gogistics@gogistics-tw.com>

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
